package co.ohmygoods.product.model.vo;

public enum ProductType {

    ANALOGUE,
    ANALOGUE_LIMITATION,
    ANALOGUE_EXCLUSIVE,
    ANALOGUE_LIMITATION_EXCLUSIVE,
    DIGITAL,
    DIGITAL_LIMITATION,
    DIGITAL_EXCLUSIVE,
    DIGITAL_LIMITATION_EXCLUSIVE;
}
