name: cd

on:
  workflow_run:
    workflows: [ci]
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: deploy services to aws
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: upload build files to aws
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "./backend/docker-compose-ci.yml, ./deploy.sh"
          target: "$HOME/config"
          overwrite: "true"

      - name: deploy via deploy.sh
        uses: appleboy/ssh-action@v1.2.1
        env:
          CHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          envs: GHCR_TOKEN, GITHUB_ACTOR, GITHUB_REPOSITORY
          script: |
            chmod +x $HOME/config/deploy.sh
            $HOME/config/deploy.sh

      - name: email notify on deploy failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_ADDRESS }}
          server_port: ${{ secrets.SMPT_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "ohmygoods aws deployment failed"
          body: "backend deployment failed after multiple retries"
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.EMAIL_SENDER }}