name: ci

on:
  push:
    branches:
      - main
      - cicd

jobs:

  artifact-build:
    runs-on: ubuntu-latest
    name: run tests and build
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout backend directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: "backend"
          sparse-checkout-cone-mode: "false"

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: run unit tests
        run: ./gradlew test --console=verbose

#      - name: run integration tests with jacoco
#        run: ./backend/gradlew intetest

      - name: build backend artifact
        run: ./gradlew build -x test --console=verbose

#      - name: upload jacoco coverage report
#        uses: actions/upload-artifact@v4
#        with:
#          name: backend-jacoco-report
#          path: ./backend/app/build/reports/jacoco/test/html

#    --- required sonarcloud ---
#      - name: run sonarqube code analysis
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: ./backend/gradlew sonar -Dsonar.login=${{ secrest.SONAR_TOKEN }}
#
#      - name: fetch sonarqube quality gate result
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
#        run: |
#          echo "fetching sonarqube quality gate status"
#          curl -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=ohmygoods_backend" | jq .

#      - name: upload sonarqube report
#        uses: actions/upload-artifact@v4
#        with:
#          name: backend-sonarqube-report
#          path: ./backend/app/build/reports/sonar/

      - name: upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: backend-artifact
          path: ./backend/app/build/libs/*.jar

  docker-build:
    name: build and push docker image
    runs-on: ubuntu-latest
    needs: artifact-build
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout backend directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: "backend"
          sparse-checkout-cone-mode: "false"

      - name: download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: .

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/app/Dockerfile-ci
          push: false
          tags: ghcr.io/${{ github.repository }}/backend-app:latest